config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :welcome, except: [:show]
  resources :results, except: [:show]

  post 'welcome/search', to: 'welcome#search'

  get "api/distance/closest_venues", to: "api/distance#closest_venues"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/api/distance_controller.rb
class Api::DistanceController < ApplicationController
  include LocationHelper

  def closest_venues
    # Api integration for closest venues for a given lat long, provided as a string comma separated
    lat_long = params[:ll]
    base_latitude = lat_long.split(",")[0].to_f
    base_longitude = lat_long.split(",")[1].to_f
    if lat_long_ok?(base_latitude, base_longitude)
      results = get_nearest_results(base_latitude, base_longitude)
      render json: {
        closest_venues: results
      }, status: 200
    else
      render json: {
        status: 400,
        message: "Invalid latitude or longitude provided, a latitude must be between -90 and 90, and a longitude must be between -180 and 180"
      }, status: 400
    end
  end

  private

  def lat_long_ok?(lat, long)
    if lat.nil? || long.nil? || lat > 90 || lat < -90 || long > 180 || long < -180
      return false
    else
      return true
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/location_helper.rb
module LocationHelper
  def get_nearest_results(base_latitude, base_longitude)
    ll = base_latitude.to_s + ',' + base_longitude.to_s
    api_key = ENV['api_key']

    # make API call with the provided lat long
    url = URI("https://api.foursquare.com/v3/places/search?ll=#{ll}")
    https = Net::HTTP.new(url.host, url.port)
    https.use_ssl = true
    request = Net::HTTP::Get.new(url)
    request["Accept"] = "application/json"
    request['Authorization'] = api_key

    response = https.request(request)

    # parse the results, calculate and store the distance from the original provided location
    results = JSON.parse(response.body)["results"]
    results.each do |result|
      latitude = result["geocodes"]["main"]["latitude"]
      longitude = result["geocodes"]["main"]["longitude"]
      x = (latitude.to_f - base_latitude) * (latitude.to_f - base_latitude)
      y = (longitude.to_f - base_longitude) * (longitude.to_f - base_longitude)
      result['calculated_distance'] = Math.sqrt(x + y)
    end

    # sort the results
    results.sort_by { |hash| hash['calculated_distance'] }
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  include LocationHelper

  def index
    @latitude = params[:latitude].to_f
    @longitude = params[:longitude].to_f
    @results = get_nearest_results(@latitude, @longitude)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  include LocationHelper

  def search
    latitude = params[:post][:latitude].to_f
    longitude = params[:post][:longitude].to_f
    redirect_to results_path(:latitude => latitude, :longitude => longitude)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Venue Finder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/results/_results_row.html.erb
 <tr>
  <td>
    <%= result['name'] %>
  </td>
 <td>
   <%= result['location']['formatted_address'] %>
 </td>
  <td>
    <% result['categories'].each do |category| %>
      <%= category['name'] %>
    <% end %>
  </td>
   <td>
     <%= result['calculated_distance'] %>
   </td>
</tr>

app/views/results/_results_table.html.erb
<div id="results-table">
  <% if @results.present? %>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Address</th>
          <th>Categories</th>
          <th>Calculated Distance</th>
        </tr>
      </thead>
      <tbody>
        <% @results.each do |result| %>
          <%= render 'results_row', result: result %>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="no-results">
      Sorry no results match your search
    </div>
  <% end %>
</div>

app/views/results/index.html.erb
<div class="container">
  <%= link_to "Back", welcome_index_path %>
  <h1>Closest Venues</h1>
  <div class="header">
    Results for location <%= @latitude %>, <%= @longitude %>:
  </div>
  <%= render 'results_table' %>
</div>

app/views/welcome/index.html.erb
<h1>Closest Venues</h1>
<p>Find the nearest venues (such as pubs, restaurants, coffee shops) to a given location provided as latitude and longitude.</p>
<%= form_for 'post', url: welcome_search_path do |f| %>
  <div class="field">
    <%= f.label "Latitude", class: "label" %>
    <div class="control">
      <%= f.number_field :latitude, max: 90, min: -90, required: true, step: :any, class: "field" %>
    </div>
  </div>
  <div class="field">
    <%= f.label "Longitude", class: "label" %>
    <div class="control">
      <%= f.number_field :longitude, max: 180, min: -180, required: true, step: :any, class: "field" %>
    </div>
  </div>
  <div class="field">
    <%= f.submit "Submit", class: "button is-primary" %>
  </div>
<% end %>